language: node_js
notifications:
  email: false
node_js:
  - node
before_install:
  - npm i -g npm@3
before_script:
  - npm prune
  - npm run cover
  # - npm run lint
  # - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  # - npm run semantic-release